<?php

use Materialize\Button\FlatButton;

$mailerTestButton = new FlatButton(
    [
        'id'    => 'mailer-alert-test-button',
        'title' => "Envoyer email de test",
        'href'  => '',
        'color' => 'secondaryTextColor',
        'icon'  => 'send'
    ]
);
?>
<div class="row">
    <ul>
        <li class="divider"></li>
    </ul>
</div>
<div class="row">
    <div class="col s12">
        <?= $mailerTestButton->getHtml() ?>
    </div>
</div>
