<?php
$scId = $args[0];
/** @var \Materialize\Button\FlatButton $submit */
$submit = $args[1];
$addButton = new \Materialize\FloatingActionButton([
    'id' => 'sequence-add',
    'icon' => 'add',
    'wrapper' => 'col s6',
    'href' => '#',
    'fixed' => true
]);
$spinner = \Materialize\WidgetFactory::makeSpinner("spinner");

$method = ($scId) ? 'put' : 'post';
$action = ($scId) ? 'api/scenarios/update' : 'api/scenarios/add';

?>
<form class="row" action="<?= $action ?>" method="<?= $method ?>">
    <div id="scenario-content">
        <div class="center-align">
            <?= $spinner->getHtml(); ?>
        </div>
    </div>
    <input type="text" name="id" id="id" value="<?= $scId ?>" hidden readonly required/>
    <?= $submit->getHtml(); ?>
    <?= $addButton->getHtml() ?>
</form>