<?php
$entity = $args[0];
$actionneursList = $args[1];
$sequence = $args[2];

?>

<div class="row">
    <div class="col s2">
        <label for="actionneur-id-<?= $sequence->id() ?>" class="active">ItemId</label>
        <input type="text" name="actionneurs[id][]" id="actionneur-id-<?= $sequence->id() ?>"
               value="<?= $sequence->id() ?>" readonly required/>
    </div>

    <div class="col s6">
        <label for="actionneur-select-<?= $sequence->id() ?>">Actionneur</label>
        <div class="select-wrapper"><span class="caret">▼</span>
            <select name="actionneurs[actionneurid][]" id="actionneur-select-<?= $sequence->id() ?>">
                <?php foreach ($actionneursList as $actionneur) : ?>
                    <?php
                    $selected = '';
                    if ($actionneur->id() === $sequence->actionneurid()) {
                        $selected = 'selected';
                    }
                    ?>
                    <option value="<?= $actionneur->id() ?>" <?= $selected ?> ><?= $actionneur->getNom() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="col s2">
        <label for="actionneur-etat-<?= $sequence->id() ?>" class="active">Etat</label>
        <input type="number"
               name="actionneurs[etat][]"
               id="actionneur-etat-<?= $sequence->id() ?>"
               value="<?= $sequence->etat() ?>" min="0" max="255"
               step="1"/>
    </div>

    <?php $id = 'scenario-sequence-delete' ?>

    <label class="active" for="<?= $id ?>">*</label>
    <i id="<?= $id ?>" class="material-icons secondaryTextColor col s2 delete">delete</i>

</div>