<link rel="apple-touch-icon" sizes="57x57" href="<?= IMG . '/apple-icon-57x57.png' ?>">
<link rel="apple-touch-icon" sizes="60x60" href="<?= IMG . '/apple-icon-60x60.png' ?>">
<link rel="apple-touch-icon" sizes="72x72" href="<?= IMG . '/apple-icon-72x72.png' ?>">
<link rel="apple-touch-icon" sizes="76x76" href="<?= IMG . '/apple-icon-76x76.png' ?>">
<link rel="apple-touch-icon" sizes="114x114" href="<?= IMG . '/apple-icon-114x114.png' ?>">
<link rel="apple-touch-icon" sizes="120x120" href="<?= IMG . '/apple-icon-120x120.png' ?>">
<link rel="apple-touch-icon" sizes="144x144" href="<?= IMG . '/apple-icon-144x144.png' ?>">
<link rel="apple-touch-icon" sizes="152x152" href="<?= IMG . '/apple-icon-152x152.png' ?>">
<link rel="apple-touch-icon" sizes="180x180" href="<?= IMG . '/apple-icon-180x180.png' ?>">
<link rel="icon" type="image/png" sizes="192x192"  href="<?= IMG . '/android-icon-192x192.png' ?>">
<link rel="icon" type="image/png" sizes="32x32" href="<?= IMG . '/favicon-32x32.png' ?>">
<link rel="icon" type="image/png" sizes="96x96" href="<?= IMG . '/favicon-96x96.png' ?>">
<link rel="icon" type="image/png" sizes="16x16" href="<?= IMG . '/favicon-16x16.png' ?>">
