<?php
/** @var \OCFram\User $user */
/** @var string $content */
$title = 'ActivAPI';
?>
<!DOCTYPE html>
<html>
<head>
    <title><?= $title ?></title>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <link rel="stylesheet" href="<?= DIST . '/index.css' ?>" type="text/css">
    <?php include("Block/favicon.phtml"); ?>
    <link rel="manifest" href="<?= ROOT . '/manifest/manifest.json' ?>">
    <script src="<?= DIST . '/index.js' ?>"></script>
</head>

<body>
    <nav class="primaryColor noselect">
        <div class="nav-wrapper textOnPrimaryColor">
            <div class="valign-wrapper">
                <a id="menubutton" data-activates="slide-out" class="button-collapse show-on-large">
                    <?php if ($user->isAuthenticated()) : ?>
                        <i class="material-icons">menu</i>
                    <?php endif; ?>
                </a>
                <?php if ($user->isAuthenticated()) : ?>
                    <i id="ioconnection"
                       class="valign material-icons z-depth-1 circle red lighten-3 red-text right">
                        fiber_manual_record
                    </i>
                <?php endif; ?>
                <div class="brand-logo center"><?= $title ?></div>
            </div>
        </div>
    </nav>
    <?php if ($user->isAuthenticated()) : ?>
    <ul id="slide-out" class="side-nav">
        <?php include("sideNav/sideNavMainPart.phtml"); ?>
    </ul>
    <?php endif; ?>
    <div id="maincontent" class="container-light">
        <?php if ($user->hasFlash()) : ?>
            <script> Materialize.toast("<?= $user->getFlash() ?>", 3000); </script>
        <?php endif; ?>
        <?= $content ?>
    </div>
    <?php if ($user->isAuthenticated()) : ?>
    <script src="<?= DIST . '/socketio.js' ?>"></script>
    <script src="<?= DIST . '/materializeTricks.js' ?>"></script>
    <script>
        $("#menubutton").sideNav({
            closeOnClick: true,
            draggable: true,
            menuWidth: 250
        });
    </script>
    <?php endif; ?>
</body>
</html>
