<?php
use Materialize\FloatingActionButton;
use Materialize\WidgetFactory;
/** @var array $args */
$thermostatPlanif = $args[0];
$modes = $args[1];
/** @var \Materialize\Button\FlatButton $submit */
$submit = $args[2];
$addButton = new FloatingActionButton([
    'id' => 'planif-add',
    'icon' => 'add',
    'wrapper' => 'col s6',
    'href' => '',
    'fixed' => true
]);
$spinner = WidgetFactory::makeSpinner("spinner");
?>
<form class="row" action="api/thermostat/planif/update" method="put">
    <div id="thermostat-planif-content">
        <div class="center-align">
            <?= $spinner->getHtml(); ?>
        </div>
    </div>
    <input type="text" name="thermostat-planif-id" id="thermostat-planif-id" value="<?= $thermostatPlanif->getId() ?>" hidden readonly required />
    <input type="text" name="thermostat-planif-nomid" id="thermostat-planif-nomid" value="<?= $thermostatPlanif->getNomid() ?>" hidden readonly required />
    <input type="text" name="thermostat-planif-jour" id="thermostat-planif-jour" value="<?= $thermostatPlanif->getJour() ?>" hidden readonly required />
    <?= $submit->getHtml(); ?>
    <?= $addButton->getHtml() ?>
</form>
<template id="timetable-row-layout">
    <div class="row thermostat-planif-row">
        <fieldset class="valign-wrapper">
            <div class="col s4">
                <input class="timepicker thermostat-planif-time" type="text" id="thermostat-planif-time-" value="" required>
            </div>
            <div class="col s6">
                <div class="select-wrapper"><span class="caret">▼</span>
                    <select id="thermostat-planif-modeId-" class="thermostat-planif-modeId"></select>
                </div>
            </div>
            <div class="col s2">
                <i class="material-icons secondaryTextColor col s2 delete thermostat-planif-row-delete">delete</i>
            </div>
        </fieldset>
    </div>
</template>

<script>
    window.thermostatModes = <?= json_encode($modes) ?>
</script>