<?php


namespace App\Backend\Modules\Cache\Command;

use App\Backend\Modules\Cache\Command\Executor\Flush;
use SFram\Console\BaseCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class FlushCommand
 * @package App\Backend\Modules\Cache\Command
 */
class FlushCommand extends BaseCommand
{
    protected static $defaultName = 'cache:flush';

    protected function configure()
    {
        $this->setDescription('Flush all cache files');
    }

    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
     * @throws \Exception
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $flushExecutor = new Flush();
        if (!$files = $flushExecutor->execute($this->app)) {
            $output->writeln('No Files Deleted!');
            return 0;
        }

        $output->writeln('Files Deleted :');
        $output->writeln($files);

        return 0;
    }

    public function getName()
    {
        return parent::getName(); // TODO: Change the autogenerated stub
    }
}
