<?php
$actId = $args[0];
/** @var \Materialize\Button\FlatButton $submit */
$submit = $args[1];
$spinner = \Materialize\WidgetFactory::makeSpinner("spinner");

$method = ($actId) ? 'put' : 'post';
$action = ($actId) ? 'api/actions/update' : 'api/actions/add';

?>
<form class="row" action="<?= $action ?>" method="<?= $method ?>">
    <div id="action-content">
        <div class="center-align">
            <?= $spinner->getHtml(); ?>
        </div>
    </div>
    <input type="text" name="id" id="id" value="<?= $actId ?>" hidden readonly required/>
    <?= $submit->getHtml(); ?>
</form>