<?php

use Materialize\Icon\Icon;
use Materialize\Sidenav\Link;
use Materialize\Sidenav\Sidenav;
use Materialize\Sidenav\Subheader;

$iconNames = [
    'home', 'settings_power', 'leak_add', 'list', 'assessment', 'settings', 'play_arrow', 'local_movies', 'movies','build'
];

$icons = [];
foreach ($iconNames as $name) {
    $icon = new Icon(['name' => $name]);
    $icons[$name] = $icon->getHtml();
}

$icons['table'] = '<i class="valign col s2 mdi mdi-table"></i>';
$icons['timetable'] = '<i class="valign col s2 mdi mdi-timetable"></i>';

$accueilLink = new Link([
    'id' => 'accueil',
    'title' => 'Accueil',
    'link' => '/',
    'icon' => $icons['home']
]);

$sidenav = new Sidenav(
    [
        'subHeaders' => [
            new Subheader(
                [
                    'title' => 'Gestion',
                    'links' => [
                        new Link([
                            'id' => 'actionneurs',
                            'title' => 'Actionneurs',
                            'link' => '/actionneurs',
                            'icon' => $icons['settings_power']
                        ]),
                        new Link([
                            'id' => 'sensors',
                            'title' => 'Sensors',
                            'link' => '/sensors',
                            'icon' => $icons['leak_add']
                        ])

                    ]
                ]
            ),
            new Subheader(
                [
                    'title' => 'Scenarios',
                    'links' => [
                        new Link([
                            'id' => 'scenarios',
                            'title' => 'Scenarios',
                            'link' => '/scenarios',
                            'icon' => $icons['play_arrow']
                        ]),
                        new Link([
                            'id' => 'sequences',
                            'title' => 'Séquences',
                            'link' => '/sequences',
                            'icon' => $icons['local_movies']
                        ]),
                        new Link([
                            'id' => 'actions',
                            'title' => 'Actions',
                            'link' => '/actions',
                            'icon' => $icons['movies']
                        ])

                    ]
                ]
            ),
            new Subheader(
                [
                    'title' => 'Mesures',
                    'links' => [
                        new Link([
                            'id' => 'mesures',
                            'title' => 'Données',
                            'link' => '/mesures',
                            'icon' => $icons['list']
                        ]),
                        new Link([
                            'id' => 'graphs',
                            'title' => 'Graphs',
                            'link' => '/graphs',
                            'icon' => $icons['assessment']
                        ])
                    ]
                ]
            ),
            new Subheader(
                [
                    'title' => 'Thermostat',
                    'links' => [
                        new Link([
                            'id' => 'thermostat',
                            'title' => 'Paramètres',
                            'link' => '/thermostat',
                            'icon' => $icons['settings']
                        ]),
                        new Link([
                            'id' => 'thermostat-log',
                            'title' => 'Log',
                            'link' => '/thermostat-log',
                            'icon' => $icons['list']
                        ]),
                        new Link([
                            'id' => 'thermostat-planif',
                            'title' => 'Planif',
                            'link' => '/thermostat-planif',
                            'icon' => $icons['timetable']
                        ]),
                        new Link([
                            'id' => 'thermostat-modes',
                            'title' => 'Modes',
                            'link' => '/thermostat-modes',
                            'icon' => $icons['table']
                        ])

                    ]
                ]
            ),
            new Subheader(
                [
                    'title' => 'Système',
                    'links' => [
                        new Link([
                            'id' => 'console',
                            'title' => 'Console',
                            'link' => '/console',
                            'icon' => $icons['table']
                        ]),
                        new Link([
                            'id' => 'crontab',
                            'title' => 'Crontab',
                            'link' => '/crontab',
                            'icon' => $icons['timetable']
                        ]),
                        new Link([
                            'id' => 'configuration',
                            'title' => 'Configuration',
                            'link' => '/configuration',
                            'icon' => $icons['build']
                        ]),
                    ]
                ]
            )
        ]
    ]
);

?>

<li>
    <div class="primaryColor valign-wrapper">
        <a href="<?= ROOT ?>/" class="valign ">
            <div id="titleNav" class="flow-text textOnPrimaryColor">ActivApi</div>
        </a>
    </div>
</li>

<?= $accueilLink->getHtml(); ?>
<?= $sidenav->getHtml(); ?>
