<li>
    <div class="primaryColor valign-wrapper">
        <a href="<?= ROOT ?>/" class="valign ">
            <div id="titleNav" class="flow-text textOnPrimaryColor">ActivApi</div>
        </a>
    </div>
</li>

<li>
    <a id="accueil" href="<?= ROOT ?>/" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons">home</i>
            <div class="valign col s10 flow-text">Accueil</div>
        </div>
    </a>
</li>

<li class="divider"></li>

<li><a class="subheader">Gestion</a></li>

<li>
    <a id="actionneurs" href="<?= ROOT ?>/actionneurs" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons ">settings_power</i>
            <div class="valign col s10 flow-text">Actionneurs</div>
        </div>
    </a>
</li>

<li>
    <a id="sensors" href="<?= ROOT ?>/sensors" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons ">leak_add</i>
            <div class="valign col s10 flow-text">Sensors</div>
        </div>
    </a>
</li>

<li class="divider"></li>

<li><a class="subheader">Scénarios</a></li>

<li>
    <a id="scenarios" href="<?= ROOT ?>/scenarios" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons ">play_arrow</i>
            <div class="valign col s10 flow-text">Scénarios</div>
        </div>
    </a>
</li>

<li>
    <a id="sequences" href="<?= ROOT ?>/sequences" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons ">local_movies</i>
            <div class="valign col s10 flow-text">Séquences</div>
        </div>
    </a>
</li>

<li>
    <a id="actions" href="<?= ROOT ?>/actions" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons ">movies</i>
            <div class="valign col s10 flow-text">Actions</div>
        </div>
    </a>
</li>

<li class="divider"></li>

<li><a class="subheader">Mesures</a></li>

<li>
    <a id="mesures" href="<?= ROOT ?>/mesures" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons">list</i>
            <div class="valign col s10 flow-text">Donnees</div>
        </div>
    </a>
</li>

<li>
    <a id="graphs" href="<?= ROOT ?>/graphs" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons ">assessment</i>
            <div class="valign col s10 flow-text">Graphs</div>
        </div>
    </a>
</li>

<li class="divider"></li>

<li><a class="subheader">Thermostat</a></li>

<li>
    <a id="thermostat" href="<?= ROOT ?>/thermostat" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons">settings</i>
            <div class="valign col s10 flow-text">Paramètres</div>
        </div>
    </a>
</li>

<li>
    <a id="thermostat-log" href="<?= ROOT ?>/thermostat-log" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 material-icons">list</i>
            <div class="valign col s10 flow-text">Log</div>
        </div>
    </a>
</li>

<li>
    <a id="thermostat-planif" href="<?= ROOT ?>/thermostat-planif" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 mdi mdi-timetable"></i>
            <div class="valign col s10 flow-text">Planif</div>
        </div>
    </a>
</li>

<li>
    <a id="thermostat-modes" href="<?= ROOT ?>/thermostat-modes" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 mdi mdi-table"></i>
            <div class="valign col s10 flow-text">Modes</div>
        </div>
    </a>
</li>

<li class="divider"></li>

<li><a class="subheader">Outils</a></li>

<li>
    <a id="console" href="<?= ROOT ?>/console" class="waves-effect waves-pink waves-ripple">
        <div class="valign-wrapper row">
            <i class="valign col s2 mdi mdi-table"></i>
            <div class="valign col s10 flow-text">Console</div>
        </div>
    </a>
</li>

<footer style="height: 100px;"></footer>
