CREATE TABLE IF NOT EXISTS notification
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entityId INTEGER NOT NULL,
    entityType VARCHAR(1024) NOT NULL,
    alertType VARCHAR(1024) NOT NULL,
    sent INTEGER DEFAULT 0
);
