DROP TABLE IF EXISTS scenario;
DROP TABLE IF EXISTS scenario_corresp;
DROP TABLE IF EXISTS sequence;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS sequence_item;

CREATE TABLE IF NOT EXISTS scenario 
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS sequence 
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nom VARCHAR(100) NOT NULL UNIQUE,
    scenarioId INT NOT NULL,
    FOREIGN KEY (scenarioId) REFERENCES scenario (id) 
);

CREATE TABLE IF NOT EXISTS item 
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    actionneurId INTEGER NOT NULL,
    etat INTEGER NOT NULL,
    FOREIGN KEY (actionneurId) REFERENCES actionneurs (id) 
);

CREATE TABLE IF NOT EXISTS sequence_item 
(
    sequenceId INTEGER NOT NULL,
    itemId INTEGER NOT NULL,
    FOREIGN KEY (sequenceId) REFERENCES "sequence" (id),
    FOREIGN KEY (itemId) REFERENCES "item" (id)
);

